version: '3'
services:
  watermill:
    image: golang:1.12
    command: /bin/true
    volumes:
      - .:/app
      - .mod-cache:/go/pkg/mod
    working_dir: /app

    environment:
      WATERMILL_TEST_MYSQL_HOST: mysql:3306
      WATERMILL_TEST_POSTGRES_HOST: postgres:5432


