name: ci
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19.1'
      - run: make build
  tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19.1'
      - run: |
          [ -f docker-compose.yml ] && docker-compose up -d || true
      - run: make test
      - run: make test_short
      - run: make test_race
      - run: make test_stress

